name: secretosx
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secretosx_app
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./:/var/www
      - ./api/vendor:/var/www/api/vendor
      - ./api/.env:/var/www/api/.env  # Asegurar que el .env se monte correctamente
    networks:
      - secretosx_network
    command: >
      sh -c "composer install --no-dev --optimize-autoloader && php-fpm"

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: secretosx_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - secretosx_network

networks:
  secretosx_network:
    driver: bridge
