version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secretosx_app
    restart: unless-stopped
    volumes:
      - ./api:/var/www/api
      - ./api/vendor:/var/www/api/vendor
    networks:
      - secretosx_network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: secretosx_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - secretosx_network
    depends_on:
      - app

networks:
  secretosx_network:
    driver: bridge