services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secretosx_app
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - .:/var/www  # Monta todo el proyecto en el contenedor
    networks:
      - secretosx_network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Esperando a que se monte el volumen..."
        sleep 5
        ls -lah /var/www/api
        if [ -f /var/www/api/composer.json ]; then
          composer install --no-dev --optimize-autoloader
        else
          echo "composer.json NO ENCONTRADO en /var/www/api"
        fi
        php-fpm

  webserver:
    image: nginx:alpine
    container_name: secretosx_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - secretosx_network

networks:
  secretosx_network:
    driver: bridge
